name: Deploy

on:
  push:
    branches:
      - master
      - export_quotes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Check dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/common.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 .app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 .app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Deploy
      run: |
        sed -i "s|%USERNAME%|${{secrets.SSH_USER}}|" etc/supervisor.conf

        pip install Fabric3
        fab -H ${{secrets.DESTINATION_HOST}} -u ${{secrets.SSH_USER}} -p ${{secrets.SSH_PASS}} prepare_destination_host
        fab -H ${{secrets.DESTINATION_HOST}} -u ${{secrets.SSH_USER}} -p ${{secrets.SSH_PASS}} deployment
